-- Insert courses data
INSERT INTO courses (title, category, level, duration, enrolled, rating, instructor, image, description, tags)
VALUES
  (
    'Introduction to Web Development',
    'Coding',
    'Beginner',
    '8 weeks',
    1240,
    4.8,
    'Alex Morgan',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97',
    'Learn the fundamentals of HTML, CSS, and JavaScript to build responsive websites. Master modern web development practices and create your first portfolio project.',
    ARRAY['HTML', 'CSS', 'JavaScript', 'Web Development']
  ),
  (
    'Python Programming Fundamentals',
    'Coding',
    'Beginner',
    '10 weeks',
    1560,
    4.9,
    'Dr. Sarah Chen',
    'https://images.unsplash.com/photo-1649180556628-9ba704115795',
    'Start your programming journey with Python. Learn syntax, data structures, functions, and object-oriented programming. Build practical projects and automate tasks.',
    ARRAY['Python', 'Programming', 'Data Structures', 'OOP']
  ),
  (
    'Data Science with Python',
    'Coding',
    'Intermediate',
    '12 weeks',
    980,
    4.7,
    'Dr. Michael Rodriguez',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
    'Master data analysis, visualization, and machine learning with Python. Learn pandas, NumPy, Matplotlib, and scikit-learn. Work on real-world data science projects.',
    ARRAY['Python', 'Data Science', 'Machine Learning', 'Data Analysis']
  ),
  (
    'Machine Learning Fundamentals',
    'Coding',
    'Advanced',
    '14 weeks',
    850,
    4.8,
    'Prof. James Wilson',
    'https://images.unsplash.com/photo-1620712943543-bcc4688e7485',
    'Deep dive into machine learning algorithms, neural networks, and deep learning. Implement models using TensorFlow and PyTorch. Build and deploy ML applications.',
    ARRAY['Machine Learning', 'Deep Learning', 'AI', 'Neural Networks']
  ),
  (
    'Mobile App Development',
    'Coding',
    'Intermediate',
    '12 weeks',
    1120,
    4.6,
    'Emily Thompson',
    'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c',
    'Learn to build cross-platform mobile applications using React Native. Master mobile UI/UX design, state management, and app deployment to iOS and Android.',
    ARRAY['React Native', 'Mobile Development', 'JavaScript', 'App Design']
  ),
  (
    'Full Stack Development',
    'Coding',
    'Advanced',
    '16 weeks',
    920,
    4.7,
    'David Kumar',
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
    'Become a full-stack developer by mastering both frontend and backend technologies. Learn React, Node.js, Express, and MongoDB. Build complete web applications.',
    ARRAY['Full Stack', 'React', 'Node.js', 'MongoDB']
  ),
  (
    'Sustainable Farming Techniques',
    'Farming',
    'Intermediate',
    '12 weeks',
    890,
    4.9,
    'Maria Chen',
    'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad',
    'Master organic farming methods, crop rotation, and sustainable pest management. Learn to create and maintain eco-friendly farming systems.',
    ARRAY['Organic', 'Sustainable', 'Agriculture', 'Crop Management']
  ),
  (
    'Urban Vertical Farming',
    'Farming',
    'Beginner',
    '8 weeks',
    720,
    4.7,
    'Dr. Lisa Wong',
    'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae',
    'Learn to grow food in urban spaces using vertical farming techniques. Master space optimization, lighting systems, and hydroponic setups for city environments.',
    ARRAY['Urban Farming', 'Vertical Gardens', 'Hydroponics', 'Space Optimization']
  ),
  (
    'Traditional Handicraft Creation',
    'Handicrafts',
    'Beginner',
    '6 weeks',
    760,
    4.7,
    'Raj Patel',
    'https://plus.unsplash.com/premium_photo-1679809447923-b3250fb2a0ce',
    'Learn to create beautiful handcrafted items using traditional techniques. Master various crafting methods and create unique pieces.',
    ARRAY['Crafts', 'Traditional', 'Artisan', 'Handmade']
  ),
  (
    'Sustainable Textile Design',
    'Handicrafts',
    'Intermediate',
    '10 weeks',
    680,
    4.8,
    'Emma Thompson',
    'https://images.unsplash.com/photo-1513519245088-0e12902e5a38',
    'Create eco-friendly textiles using natural dyes and sustainable materials. Learn traditional weaving techniques and modern sustainable practices.',
    ARRAY['Textile Design', 'Natural Dyes', 'Sustainable Fashion', 'Weaving']
  ),
  (
    'Digital Illustration',
    'Design',
    'Intermediate',
    '8 weeks',
    980,
    4.7,
    'Jamie Lee',
    'https://images.unsplash.com/photo-1572044162444-ad60f128bdea',
    'Create stunning digital illustrations using industry-standard tools and techniques. Master digital art fundamentals and professional workflows.',
    ARRAY['Design', 'Digital Art', 'Illustration', 'Creative']
  ),
  (
    'Sustainable Product Design',
    'Design',
    'Advanced',
    '12 weeks',
    590,
    4.9,
    'Carlos Rodriguez',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    'Design eco-friendly products using sustainable materials and manufacturing processes. Learn circular design principles and life cycle assessment.',
    ARRAY['Product Design', 'Sustainability', 'Circular Design', 'Eco-friendly']
  ),
  (
    'Social Entrepreneurship',
    'Business',
    'Intermediate',
    '10 weeks',
    850,
    4.8,
    'Dr. Sarah Johnson',
    'https://images.unsplash.com/photo-1552664730-d307ca884978',
    'Learn to build and scale businesses that create positive social impact. Master sustainable business models, impact measurement, and social innovation.',
    ARRAY['Entrepreneurship', 'Social Impact', 'Business Strategy', 'Sustainability']
  ),
  (
    'Sustainable Business Management',
    'Business',
    'Advanced',
    '14 weeks',
    720,
    4.7,
    'Michael Chen',
    'https://images.unsplash.com/photo-1553877522-43269d4ea984',
    'Master sustainable business practices, green supply chain management, and corporate social responsibility. Learn to lead eco-conscious organizations.',
    ARRAY['Business Management', 'Sustainability', 'CSR', 'Green Business']
  ),
  (
    'Hydroponic Gardening',
    'Farming',
    'Advanced',
    '9 weeks',
    640,
    4.8,
    'David Miller',
    'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac',
    'Build and maintain hydroponic systems for urban farming and sustainable food production. Master advanced growing techniques and system optimization.',
    ARRAY['Hydroponics', 'Urban Farming', 'Sustainability', 'System Design']
  ); 